### PR TITLE
Use github action for the CI

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by xXx-caillou-xXx** [comment]
Never used the github actions, but they do seems to be better integrated than the gitlab-ci we are currently using.

**Review by xXx-caillou-xXx — APPROVED** [review]
I see that we are ditching alpine haha

**Review by wargio — APPROVED** [review]
LGTM

**Comment by kpcyrd** [comment]
if dropping alpine wasn't intentional I can help adding them back in :)

**Comment by jvoisin** [comment]
It wasn't intentional at all :)

**Pull request merged**
