### PR TITLE
Fix #368 build with system libpcre

### LINKED ISSUE #368: Compatibility with PHP < 7.3 with system libpcre
Seems broken

` undefined symbol: php_pcre_exec`

This symbol is only available when PHP is build with bundled libpcre
which is not the case in most distro packages.

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by wargio** [comment]
does this build on newer versions of PHP ?

**Comment by remicollet** [comment]
Yes, tested with PHP 7.0 to 8.0, some with bundled libpcre (old RHEL), some with system libpcre (Fedora)

**Comment by wargio** [comment]
Nice!

**Review by wargio — APPROVED** [review]

**Review by jvoisin — APPROVED** [review]

**Comment by jvoisin** [comment]
@remicollet What distributions would you like us to use in the CI to make your life easier? Latest fedora with latest php available there?

**Comment by remicollet** [comment]
> @remicollet What distributions would you like us to use in the CI to make your life easier? Latest fedora with latest php available there?

Yes, the latest Fedora with PHP from distro may help.

BTW, I have a quite big build matrix
* Fedora 31 to 33
* RHEL / CentOS 7.9 and 8.3
* PHP 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0

**Comment by jvoisin** [comment]
Done in https://github.com/jvoisin/snuffleupagus/commit/8ce3a93137689fa7e5496981f44a0ecd763e1a99

**Pull request merged**
